### ISSUE TITLE
Current master panic

### ISSUE THREAD

**Issue by clburlison** [airbnb/gosal#39]
I wasn't able to follow up on the fix for this but it looks like the current commit in master 7d07069 causes a panic when trying to build the windows report. Looks like the latest stable commit is d6863b5.

If I have time to dig deeper into this issue I'll offer a PR.

```go
PS C:\Shared> .\gosal-7d07069.exe --config .\config.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x6e5d15]
goroutine 1 [running]:
github.com/airbnb/gosal/xpreports/windows.BuildBase64bz2Report(0xc04206acc0, 0x1087abea4df765a2, 0xc042168540, 0x24, 0x0)
        /Users/clburlison/go/src/github.com/airbnb/gosal/xpreports/windows/base64bz2.go:27 +0x45
github.com/airbnb/gosal/xpreports.buildReport(0xc04206acc0, 0xc0420ac180, 0x80, 0xc042112000)
        /Users/clburlison/go/src/github.com/airbnb/gosal/xpreports/build_windows.go:26 +0xde
github.com/airbnb/gosal/xpreports.Build(0xc04206acc0, 0xc04206af30, 0x0, 0x0)
        /Users/clburlison/go/src/github.com/airbnb/gosal/xpreports/reports.go:26 +0x32
github.com/airbnb/gosal/sal.SendCheckin(0xc04206acc0, 0xc042073d00, 0xc042073cd0)
        /Users/clburlison/go/src/github.com/airbnb/gosal/sal/sal.go:94 +0x78
main.createRootCmd.func1(0xc04209cb40, 0xc0420e0800, 0x0, 0x2)
        /Users/clburlison/go/src/github.com/airbnb/gosal/cmd/gosal/gosal.go:47 +0x3d
github.com/airbnb/gosal/vendor/github.com/spf13/cobra.(*Command).execute(0xc04209cb40, 0xc042050090, 0x2, 0x3, 0xc04209cb40, 0xc042050090)
        /Users/clburlison/go/src/github.com/airbnb/gosal/vendor/github.com/spf13/cobra/command.go:702 +0x2cd
github.com/airbnb/gosal/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04209cb40, 0x0, 0xc04209cd80, 0xc04209cc80)
        /Users/clburlison/go/src/github.com/airbnb/gosal/vendor/github.com/spf13/cobra/command.go:783 +0x2eb
github.com/airbnb/gosal/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04209cb40, 0xc042073f70, 0x1)
        /Users/clburlison/go/src/github.com/airbnb/gosal/vendor/github.com/spf13/cobra/command.go:736 +0x32
main.main()
        /Users/clburlison/go/src/github.com/airbnb/gosal/cmd/gosal/gosal.go:90 +0xf8
```

**Comment by 1dustindavis** [comment]
I didn't spend a ton of time testing, but I was not able to reproduce this running `7d07069` on Windows 10 1803.

**Comment by bdemetris** [comment]
same, I can't reproduce on `17134.471` version 1803

im going to run through a few of the combinations of windows versions available to me and see if I can crack it.

@clburlison if you get a moment can you paste over your config file?  im just curious if you're using the `management` block or not since thats the last thing introduced that could be causing you issues (just a guess at this point)

**Comment by clburlison** [comment]
Please disregard. I don't know what I was doing 3 months ago but a fresh clone resulted in a proper build so 🤷‍♂️
